### ISSUE TITLE
Failed to get download url

### ISSUE THREAD

**Issue by CreativeMD** [SrTobi/BeeDownloader#1]
Hey, i tried to use your BeeDownloader, but there seems to be an url mismatch:

example url: "https://www.youtube.com/watch?v=bM7SZ5SBzyY"
causes this issue:
![image](http://i.imgur.com/u2YzQ3q.png)

**Comment by SrTobi** [comment]
Year think dependencies have to be updated. Will do it later today

**Comment by SrTobi** [comment]
@CreativeMD I made a new release. Tell me if it works for you

**Comment by CreativeMD** [comment]
yes it's working. Great job! and thank you very much :D
